### PR TITLE
Use pre-built Docker image for erd

### LINKED ISSUE #1084: Docker containers for more platforms
Besides `x68_64` aka `amd64`, various ARM platforms are being used for servers or development (Raspberry, Mac, AWS, …). The current docker build process can only build for the developer machine's architecture, typically `amd64`. This is then also what is published as a docker image on Docker Hub. As a result, ARM servers cannot use the docker image; a complete build system has to be set up on the ARM server before Kroki can be run.

Docker supports multi-architecture images seamlessly and efficiently; clients will transparently request the correct image for their architecture, if that architecture is available. For example, [Debian base images are available in up to 9 architectures](https://hub.docker.com/_/debian?tab=tags).

If the underlying code runs on multiple architectures as well, then [it is easy to build a multi-architecture docker image](https://netfuture.ch/2020/05/multi-arch-docker-image-easy/), [e.g., in Knot DNS](https://gitlab.nic.cz/knot/knot-dns/-/commit/a87fcc160cf7cc34bc93bb1d339a5e802b4751b6). If not, [these issues need to be sorted out first](https://github.com/SteveLTN/https-portal/pull/256). 

As most of the code is Java, Python, or JavaScript, I would expect the changes to be straightforward.

(Spin-off of #1066 discussion)

### LINKED ISSUE #1239: Error generating `erd` with Docker on ARM
Follow-up to https://github.com/yuzutech/kroki/issues/1221.

It is not possible to generate `erd` diagrams when using Docker on ARM.
Image Tag [0.17.0-rc.5](https://hub.docker.com/layers/kroki/yuzutech/kroki/0.17.0-rc.5/images/sha256-69d31d632846abcc86f5c69a6f8413fe5efb013c5ef917a556ac269862899feb?context=explore).

Trying with the sample syntax on https://kroki.io:

```
curl http://localhost:8000/erd/svg --data-binary '@project.erd'
Error 500:  (exit code 137)%
```

### PR DESCRIPTION
**Pull request by felixvanoost**
Replaces the `kroki-builder-erd` Docker image used to build the `erd` binary with a pre-built image published upstream. This resolves the issue with using `erd` on ARM64 machines described in #1239 and #1084, and should slightly reduce the build time of the Kroki Docker images.

The maintainer of https://github.com/BurntSushi/erd merged my PR to publish a `linux/arm64` Docker image in October 2023 but didn't complete setting up the required ARM64 runner. There's been no further progress since then, so I've created a fork of the project and [published the images](https://github.com/felixvanoost/erd/pkgs/container/erd) myself.

@ggrossetie I'm happy to transfer ownership of the fork to you if you'd like to maintain control over it.

Closes #1239 
Closes #1084

### CODE REVIEW

**Comment by ggrossetie** [comment]
Hey! thanks for moving this issue forward.

I'm not familiar with the GitHub container repository. Do I need to do something special to activate it?
I guess I will need to update the GitHub Action to use my own ARM64 runner right? Currently, the build is using `buildjet-4vcpu-ubuntu-2204-arm`. I guess I won't have access to this runner once the project has been transferred to the yuzutech org?



Also, I've noticed that you have a `unknown/unknown` arch:
image

**Comment by felixvanoost** [comment]
The GitHub container registry should be enabled by default; you don't have to do anything special. All you should need to do is change to your local ARM runner as you described, then update the URL of the image in the Dockerfile.

**Comment by ggrossetie** [comment]
@felixvanoost sent you an invite to join the @yuzutech organization, you should be able to transfer the repository

**Comment by felixvanoost** [comment]
@ggrossetie I tried transferring ownership of the repo but I get an error message saying that I need permissions to create public repositories in @yuzutech first.

**Comment by ggrossetie** [comment]
@felixvanoost I've allowed repository creation, could you please try again? Ref: https://docs.github.com/en/organizations/managing-organization-settings/setting-permissions-for-deleting-or-transferring-repositories

**Comment by felixvanoost** [comment]
> @felixvanoost I've allowed repository creation, could you please try again? Ref: https://docs.github.com/en/organizations/managing-organization-settings/setting-permissions-for-deleting-or-transferring-repositories

I successfully transferred it last night. 🚀

**Comment by ggrossetie** [comment]
Container image is now available in https://github.com/yuzutech/erd/pkgs/container/erd/257247359?tag=v0.2.3

**Comment by felixvanoost** [comment]
@ggrossetie Good to go!

**Comment by ggrossetie** [comment]
Many thanks for your work 🙇🏻

**Pull request merged**
