### PR TITLE
remove the include part in c4 .puml files

### PR DESCRIPTION
**Pull request by lind**
To resolve https://github.com/yuzutech/kroki/issues/718

### CODE REVIEW

**Comment by lind** [comment]
@Mogztter Some whitespaces removed as well

**Comment by Mogztter** [comment]
Looks good!
It would be great to add a test case to make sure that we don't rely on the network but it might be a bit tricky to test... 🤔 
I will give it some thought... maybe we could set `socksProxyHost` and `socksProxyPort` to a non existing proxy using `System.setProperty`?

**Comment by Mogztter** [comment]
> It would be great to add a test case to make sure that we don't rely on the network but it might be a bit tricky to test... thinking
I will give it some thought... maybe we could set socksProxyHost and socksProxyPort to a non existing proxy using System.setProperty?

Seems to be working, I've added a test

**Comment by Mogztter** [comment]
Thanks for the fix 👏🏻

**Comment by lind** [comment]
Thanks for fast response 😄 

@Mogztter Do you think this might come with a 12.2 release some time soon? It would be nice to have C4 working again with [larger Excalidraw diagrams](https://docs.kroki.io/kroki/setup/configuration/#_max_uri_length)...

**Comment by Mogztter** [comment]
The main branch already contains new "features", so it will probably be version 0.13.0 but yes I'm trying to do monthly releases.

> It would be nice to have C4 working again and larger Excalidraw diagrams.

This is already available in Kroki 0.12.0, if you are using your own instance you can use `KROKI_MAX_URI_LENGTH` to increase the max URI length.

I might increase it on the public instance.... I'm still not decided but I think I'm gonna increase it to 8192 and see what happens... if it's too much then I might revert it to the default value 4096.

**Pull request merged**
