### PR TITLE
Bumb svgbob from 0.4.2 to 0.5.3

### PR DESCRIPTION
**Pull request by hason**
Svgbob 0.5.0 supports shape tagging and styling

### CODE REVIEW

**Comment by Mogztter** [comment]
Thanks for the heads-up! :+1: 
Since we do not use a `Cargo.toml`, [dependabot](https://dependabot.com/rust/) cannot automatically detect when a new release is available.

Having said that, I would like to wait until there's a 0.5.0 stable version available.

**Comment by Mogztter** [comment]
For reference, svgbob is available on crates.io: https://crates.io/crates/svgbob 
Currently, the latest version is 0.5.0-alpha.9 (Oct 23, 2020), still no stable version.

**Comment by Mogztter** [comment]
0.5.0-alpha.11 (Nov 25, 2020)

**Comment by hason** [comment]
@Mogztter 0.5.3

**Comment by Mogztter** [comment]
Thanks @hason!

**Pull request merged**
