### PR TITLE
Option to deploy to kubernetes

### PR DESCRIPTION
**Pull request by teochenglim**
Allow to deploy to k8s using a quick method.

### CODE REVIEW

**Comment by Mogztter** [comment]
Hey @teochenglim, thanks for your contribution!

I think we should move this information into the documentation.
We are using [AsciiDoc](https://docs.asciidoctor.org/asciidoc/latest/) and [Antora](https://docs.antora.org/) to publish the documentation.

Here's what I have in mind:

1. create a `k8s` directory in https://github.com/yuzutech/kroki/tree/master/docs/modules/setup/pages
2. move `k8s/readme.md` into this new directory
3. convert the Markdown file to AsciiDoc
4. create a `examples` in https://github.com/yuzutech/kroki/tree/master/docs/modules/setup
5. move all the example files (*.yml) into the examples directory

You can then include example into the page using the `include` directive.

For instance, you can include `blockdiag-deployment.yaml` into a source block using:

```
[source,yaml]
----
include::example$blockdiag-deployment.yaml[]
----
```

If you are not familiar with AsciiDoc, take a look at: https://docs.asciidoctor.org/asciidoc/latest/asciidoc-vs-markdown/#comparison-by-example
It should help you convert the Markdown file into AsciiDoc.

Once this is done, we could also add an option to download all the files (zip) but let's first move the files in the `docs` directory.

Let me know if you have any question or if you need help to migrate the content.

**Comment by teochenglim** [comment]
I have done the following, please let me know any further feedback.

* move the sample installation files to example folder
* convert markdown to adoc
* move the docker-compose to above so the natural testing older, 1. run on local, 2. run on docker, 3. run on docker-compose, 4. run on kubernetes
*  since kubernetes setup could be very complex, I only provide the k8s object skeleton that works on most people.

suggest further work on helm chart. But in order to provide helm chart I would need a place to put the index.yml and zip file

**Comment by Mogztter** [comment]
> I have done the following, please let me know any further feedback.

Thanks, I will take a look.

> suggest further work on helm chart. But in order to provide helm chart I would need a place to put the index.yml and zip file

Let's focus on the k8s documentation for now, we can open a follow-up issue/pull request to add an help chart. I think we can use the attachments family directory: https://docs.antora.org/antora/2.3/attachments-directory/#attachments-dir (but again let's do that in a follow-up pull request)

**Comment by teochenglim** [comment]
Thank you. Looks really good now =)

**Comment by Mogztter** [comment]
@teochenglim Is there a way to test the install procedure? I'm not familiar with k8s but I've heard about k3s (https://k3s.io/) which might help running Kubernetes locally. Any suggestion?

**Comment by teochenglim** [comment]
'kind' is the best one, the 'kubernetes' project use kind too. https://github.com/kubernetes-sigs/kind

Here is some simple example for you to use kind 
https://appfleet.com/blog/local-kubernetes-testing-with-kind/
https://radu-matei.com/blog/kubernetes-e2e-github-actions/
https://github.com/marketplace/actions/kind-kubernetes-in-docker-action

simple CI as create a cluster and wait, deploy pods, and check the pod is running

```shell
kubectl get pod -l app=[app_label] | grep ready

```

or

```
$ kubectl get pod -l app=[app_label]  -o json | jq -r '.items[0].status.containerStatuses[0].ready'
true

```

or 

wait for pod to be live within timeout

```shell
$ kubectl wait --for=condition=ready pod -l app=[app_label] --timeout=10s || echo "job failed" && exit 1

```

**Comment by Mogztter** [comment]
Thanks I will give it a try :wink:

**Comment by Mogztter** [comment]
Sorry I messed up and I can't reopen this pull request :disappointed: 
I've recreated https://github.com/yuzutech/kroki/pull/616

**Pull request closed without merging**
