### PR TITLE
Update UMLet to v15.0.0

### LINKED ISSUE #1353: Update UMLet to newest Version (including documentation)
There is a new version of UMLet out in the wide (Version: 15.0.0).
If diagrams are created via this version and rendered with Kroki, the diagrams look different as when created with the 14.3.0 version of UMLet. 

This is most certainly caused by the major version update - and thus breaking changes.

We would like to update the UMLet Version in Kroki to 15.0.0.
One thing we noticed is that Kroki uses `umlet-mini.jar`, but we could not find build instructions.

It would be awesome if we could:

- [ ] Provide instructions for umlet-min build to enable open source contributions in that area
- [ ] Update UMLet Version within Kroki to 15.0.0

### PR DESCRIPTION
**Pull request by LittleHuba**
I had some time to update umlet-mini to the newer version 15.0.0. You can take a look at the used umlet-version here: https://github.com/LittleHuba/umlet-mini

I did a lot of cleanup of the commits to also help with future version upgrades.

Fixes #1353

### CODE REVIEW

**Comment by Mogztter** [comment]
Thanks!
Would it be possible to open a pull request on https://github.com/yuzutech/umlet/tree/mini ?

**Comment by LittleHuba** [comment]
Sure can do!

But I'd hesitate to merge this on top of that branch because that will remove a lot of the benefits of my work. E.g. rebasing on a newer release would again be a huge pain.

So I'd propose moving the current `mini` branch  to a different branch `mini_14_3_0` and then cloning my branch into a new branch `mini`.

Also I'm going on holiday for the next two weeks so I can only do so afterwards.

**Comment by Mogztter** [comment]
> So I'd propose moving the current mini branch to a different branch mini_14_3_0 and then cloning my branch into a new branch mini.

I'm fine with that but I want to compare/diff the code from each branch.

**Comment by LittleHuba** [comment]
I had to move my work to a new repository that was forked from your local one. The changes are the exact same. The diff is huge as expected but here you go: https://github.com/yuzutech/umlet/pull/1

**Comment by ggrossetie** [comment]
merged in https://github.com/yuzutech/kroki/pull/1456
Thanks for your great work 💪🏻

**Pull request closed without merging**
