### PR TITLE
chore(smoketests) don't expose companion container ports

### PR DESCRIPTION
**Pull request by arukiidou**
following up at https://github.com/yuzutech/kroki/pull/149

and https://github.com/yuzutech/kroki/pull/1178

The difference is that, the above is a "free" fix for the document only, 

this is fix for the test, so it's possible that it could break the test

### CODE REVIEW

**Comment by Mogztter** [comment]
@arukiidou Could you please rebase? I just merged #1178

**Comment by Mogztter** [comment]
@arukiidou smoke tests are failing because we are using `wait-for-it.sh` on port 8001, 8002, 8003 and 8004 in order to make sure that all companion containers are up and running before executing the tests suite.

https://github.com/yuzutech/kroki/blob/eabc978298641a5044b3ec85068649c139cdbacd/Makefile#L74-L78

Since ports 8001, 8002, 8003 and 8004 are not exposed on the host we will need another strategy to make sure that the companion containers are up and running.

Maybe using `wait-for-it.sh` on port 8000 and waiting 15 seconds is enough. You could try to remove lines 75 to 78 and see what happens.

**Comment by arukiidou** [comment]
> @arukiidou smoke tests are failing because we are using `wait-for-it.sh` on port 8001, 8002, 8003 and 8004 in order to make sure that all companion containers are up and running before executing the tests suite.
> 
> https://github.com/yuzutech/kroki/blob/eabc978298641a5044b3ec85068649c139cdbacd/Makefile#L74-L78
> 
> Since ports 8001, 8002, 8003 and 8004 are not exposed on the host we will need another strategy to make sure that the companion containers are up and running.
> 
> Maybe using `wait-for-it.sh` on port 8000 and waiting 15 seconds is enough. You could try to remove lines 75 to 78 and see what happens.

Success.

You have two choices. Which is better? 
- close this pr. because the smoke test are legitimate reasons to use ports, not expose. 
- Instead, test it using

```
>docker compose ps | grep -e blockdiag | grep -e running  | grep -e  8001/tcp
blockdiag           "gunicorn --preload …"   blockdiag           running             8001/tcp
>WAITFORIT_result=$?
>echo $WAITFORIT_result
0
```

**Comment by Mogztter** [comment]
Let's keep it that way, we can always revisit it if we need/want something more sophisticated.
Thanks!

**Pull request merged**
