### PR TITLE
chore(deps): update structurizr packages

### PR DESCRIPTION
**Pull request by ggrossetie**
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [com.structurizr:structurizr-core](https://togithub.com/structurizr/java) | compile | minor | `1.26.1` -> `1.29.0` |
| [com.structurizr:structurizr-export](https://togithub.com/structurizr/java) | compile | minor | `1.16.1` -> `1.19.0` |
| [com.structurizr:structurizr-dsl](https://togithub.com/structurizr/java) | compile | minor | `1.32.0` -> `1.35.0` |

---

### Release Notes

<details>
<summary>structurizr/java</summary>

### [`v1.29.0`](https://togithub.com/structurizr/java/releases/v1.29.0)

[Compare Source](https://togithub.com/structurizr/java/compare/v1.28.1...v1.29.0)

-   Adds `com.structurizr.api.AdminApiClient` as a client for the cloud service/on-premises admin APIs.
-   Adds support for inter-workspace URLs of the form `{workspace:123456}/diagrams`.
-   Deprecates `StructurizrClient` in favour of `WorkspaceApiClient`.

### [`v1.28.1`](https://togithub.com/structurizr/java/releases/v1.28.1)

[Compare Source](https://togithub.com/structurizr/java/compare/v1.28.0...v1.28.1)

-   `AbstractWorkspace.clearConfiguration()` creates a new instance rather than nulling it.

### [`v1.28.0`](https://togithub.com/structurizr/java/releases/v1.28.0)

[Compare Source](https://togithub.com/structurizr/java/compare/v1.27.0...v1.28.0)

-   Adds a flag to determine whether automatic layout has been applied or not.
-   Adds support for perspective values.
-   Adds the ability to scope and validate a workspace.

### [`v1.27.0`](https://togithub.com/structurizr/java/releases/v1.27.0)

[Compare Source](https://togithub.com/structurizr/java/compare/v1.26.1...v1.27.0)

-   Upgrades dependencies, targets Java 17.
-   Adds a 'url' property to 'RelationshipView' (see [https://github.com/structurizr/java/issues/214](https://togithub.com/structurizr/java/issues/214)).

</details>

---

### Configuration

📅 **Schedule**: At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get [config help](https://togithub.com/renovatebot/renovate/discussions) if that's undesired.

---

 - [ ] If you want to rebase/retry this PR, click this checkbox.

---

This PR has been generated by [Renovate Bot](https://togithub.com/renovatebot/renovate).

### CODE REVIEW

**Comment by arukiidou** [comment]
required java17🙃

**Comment by ggrossetie** [comment]
Blocked by #1689

**Comment by ggrossetie** [comment]
@arukiidou Are you sure about that? I cannot find any mention of that in https://github.com/structurizr/java/releases/tag/v2.0.0 ?
Also, I think you meant Structurizr 2.x requires Java 17 no? https://github.com/yuzutech/kroki/pull/1712

**Comment by arukiidou** [comment]
yes, my understanding is that java17 is required from v1.27.0+.

https://github.com/structurizr/java/releases/tag/v1.27.0

**Pull request closed without merging**
