### PR TITLE
Add Travis to project

### PR DESCRIPTION
**Pull request by groovytron**
Travis does the following:

- installs the dependencies
- builds the project with `maven`

The selected JDK is OpenJDK 12 but it can be changed for a lower version if needed.

I would have liked to add containers builds to the CI but I did not manage to build them locally for testing.

I hope it helps. Thanks in advance for your feedback.

### CODE REVIEW

**Comment by Mogztter** [comment]
Thanks @groovytron !

> I would have liked to add containers builds to the CI but I did not manage to build them locally for testing.

Did you get an error? Could you please share the steps to reproduce the issue?

> The selected JDK is OpenJDK 12 but it can be changed for a lower version if needed.

I had some issue with JDK 11 and Alpine so for now I'm still running Kroki on Alpine with JDK 8 but it should compile and run fine with JDK 12.

> I hope it helps. Thanks in advance for your feedback.

Sure it's great!
Thanks for contributing to Kroki, I really appreciate your help :+1: 

I've enabled Travis and successfully built the project on master branch: https://travis-ci.org/yuzutech/kroki/jobs/592521506

**Comment by Mogztter** [comment]
I think we can merge this pull request as is, then add the containers builds in another pull request, what do you think @groovytron ?

**Comment by groovytron** [comment]
Yes no problem. You can merge it if you are already happy with these modifications. I'll try to troubleshoot the containers builds when I have time to retry and send you at least the logs. :+1:

**Comment by Mogztter** [comment]
Thanks again @groovytron for your contribution 🚀

**Pull request merged**
