### PR TITLE
Troubleshoot SegFault on Kroki server container

### PR DESCRIPTION
**Pull request by Mogztter**

### CODE REVIEW

**Comment by Mogztter** [comment]
```
kroki_1       | #
kroki_1       | # A fatal error has been detected by the Java Runtime Environment:
kroki_1       | #
kroki_1       | #  SIGSEGV (0xb) at pc=0x00007fdb5260e980, pid=1, tid=32
kroki_1       | #
kroki_1       | # JRE version: OpenJDK Runtime Environment AdoptOpenJDK (11.0.10+9) (build 11.0.10+9)
kroki_1       | # Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (11.0.10+9, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
kroki_1       | # Problematic frame:
kroki_1       | # C  [libc.so.6+0x81980]  _IO_link_in+0x1f0
kroki_1       | #
kroki_1       | # Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to //core.1)
kroki_1       | #
kroki_1       | # An error report file with more information is saved as:
kroki_1       | # //hs_err_pid1.log
kroki_1       | #
kroki_1       | # If you would like to submit a bug report, please visit:
kroki_1       | #   AdoptOpenJDK/openjdk-support/issues
kroki_1       | # The crash happened outside the Java Virtual Machine in native code.
kroki_1       | # See problematic frame for where to report the bug.
kroki_1       | #
```

**Comment by Mogztter** [comment]
It might be because `adoptopenjdk/openjdk11:jre-11.0.10_9-alpine` now fetches packages from `https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz`:


```
2021-02-24T20:03:54.3231343Z Step 9/27 : RUN apk add --update --no-cache            libjpeg            giflib-dev            graphviz            ttf-freefont  && apk add --update --no-cache             --repository https://dl-cdn.alpinelinux.org/alpine/edge/testing/            wqy-zenhei
2021-02-24T20:03:54.3407396Z  ---> Running in 36d0f16ac8a6
2021-02-24T20:03:54.6740233Z fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
2021-02-24T20:03:54.8282242Z fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
```


I'm not sure why since the Dockerfile of `adoptopenjdk/openjdk11:jre-11.0.10_9-alpine` indicates [`FROM alpine:3.12`](https://github.com/AdoptOpenJDK/openjdk-docker/blob/50ad0095ef3128f17be7dcdb180be97651475b9d/11/jre/alpine/Dockerfile.hotspot.releases.full#L20)... I also cannot reproduce this issue locally.

Maybe a Docker bug? I will try to upgrade Docker, I'm using `v20.10.3` on my machine.

**Comment by Mogztter** [comment]
After a `docker system prune -a` I get the same result on my machine, running smoke tests...

**Comment by Mogztter** [comment]
We might need to downgrade to `adoptopenjdk/openjdk11:jre-11.0.9.1_1-alpine`:

```console
$ docker run -it adoptopenjdk/openjdk11:jre-11.0.9.1_1-alpine
Unable to find image 'adoptopenjdk/openjdk11:jre-11.0.9.1_1-alpine' locally
jre-11.0.9.1_1-alpine: Pulling from adoptopenjdk/openjdk11
801bfaa63ef2: Pull complete 
f048df428f87: Pull complete 
d922b2b1f18d: Pull complete 
Digest: sha256:b6ab039066382d39cfc843914ef1fc624aa60e2a16ede433509ccadd6d995b1f
Status: Downloaded newer image for adoptopenjdk/openjdk11:jre-11.0.9.1_1-alpine
/ # cat /etc/*release*
3.12.3
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.12.3
PRETTY_NAME="Alpine Linux v3.12"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
/ # 
```

For reference, here's the result with `adoptopenjdk/openjdk11:jre-11.0.10_9-alpine`:

```console
$ docker run -it adoptopenjdk/openjdk11:jre-11.0.10_9-alpine 
/ # cat /etc/*release*
3.13.2
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.13.2
PRETTY_NAME="Alpine Linux v3.13"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/
```

**Comment by Mogztter** [comment]
Upstream issue: https://github.com/AdoptOpenJDK/openjdk-docker/issues/520

**Comment by lind** [comment]
> /cc @lind Took me a few hours but I finally found the root cause :sweat_smile: 

Well done! 👏

**Pull request merged**
