### PR TITLE
fix: add oci labels to other images

### PR DESCRIPTION
**Pull request by MindTooth**
This way we can have them automatically grouped when e.g. using Renovate.

```
org.opencontainers.image.source="https://github.com/yuzutech/kroki"
```
is the important bit.

### CODE REVIEW

**Comment by MindTooth** [comment]
However, it might be better to set the common ones in the bake file and only override individual container. 🤔   I'll look into this instead.

**Comment by MindTooth** [comment]
I reworked it to insert them via bake.  I am unable to run `make buildServer` and `make buildDockerImages` as it crashes somehow.

I'm on macOS M1, and Java 21.  So guess something is up. 🤔

**Comment by ggrossetie** [comment]
Thanks for your contribution! Let's see how it goes in the CI 😄

**Pull request merged**
