### PR TITLE
remove [Setup Docker] step

### PR DESCRIPTION
**Pull request by arukiidou**
Remove [Setup Docker] step, setup-buildx-action is preferred

- Reduce steps 
- Version matching between client and server

Example: https://github.com/arukiidou/sshpass-docker/blob/main/.github/workflows/main.yaml

### CODE REVIEW

**Comment by Mogztter** [comment]
Nice!
I guess we should also remove it from: https://github.com/yuzutech/kroki/blob/1d2efaffe7c69efd3cf69e62bd0eb523b5aa682d/.github/workflows/release.yml#L57-L59

**Comment by arukiidou** [comment]
> Nice! I guess we should also remove it from:
> 
> https://github.com/yuzutech/kroki/blob/1d2efaffe7c69efd3cf69e62bd0eb523b5aa682d/.github/workflows/release.yml#L57-L59

ok, fixed✅

**Comment by arukiidou** [comment]
something happened. reopen  and try again

**Comment by Mogztter** [comment]
> something happened. reopen and try again

Yeah, looks like a timeout/temporary issue

**Comment by Mogztter** [comment]
Thank you 😃

**Pull request merged**
