### PR TITLE
WireViz support

### LINKED ISSUE #282: Add support for Wire diagrams
#### Input
```yml
connectors:
  X1:
    type: D-Sub
    subtype: female
    pinout: [DCD, RX, TX, DTR, GND, DSR, RTS, CTS, RI]
  X2:
    type: Molex KK 254
    subtype: female
    pinout: [GND, RX, TX]

cables:
  W1:
    gauge: 0.25 mm2
    length: 0.2
    color_code: DIN
    wirecount: 3
    shield: true

connections:
  -
    - X1: [5,2,1]
    - W1: [1,2,3]
    - X2: [1,3,2]
  -
    - X1: 5
    - W1: s
```
#### Output
demo01

Format:

- `mywire.gv`         GraphViz output
- `mywire.svg`        Wiring diagram as vector image
- `mywire.png`        Wiring diagram as raster image
- `mywire.bom.tsv`    BOM (bill of materials) as tab-separated text file
- `mywire.html`       HTML page with wiring diagram and BOM embedded

We can start by supporting png and svg.

#### Runtime

Python 3.7

#### Project

https://github.com/formatc1702/WireViz

### PR DESCRIPTION
**Pull request by copyrights**
Add support for [WireViz](https://github.com/formatc1702/WireViz) .

this pull request is based on @jhogendorn's https://github.com/jhogendorn/kroki-wireviz 
 
closes #282

### CODE REVIEW

**Comment by ggrossetie** [comment]
Awesome, thanks!

> have you decided when ever to you one companion per library or per technology stack?

I'm leaning toward one companion container per library.  
Besides, if someone want to create a single companion container per technology stack they will be able to register it using https://github.com/yuzutech/kroki/issues/1423 (so technically both options will be supported)

**Comment by copyrights** [comment]
Ok, should I extract wireviz into a separate container?

**Comment by ggrossetie** [comment]
Yes please!

**Comment by copyrights** [comment]
@ggrossetie done. please review.

**Comment by copyrights** [comment]
test-containers job should pass with b852ec0. This time I've tested it in my fork first https://github.com/copyrights/kroki/actions/runs/4058513825/jobs/6985528299

**Comment by copyrights** [comment]
Docs CI has a chicken-and-egg issue :laughing:

**Comment by ggrossetie** [comment]
> Docs CI has a chicken-and-egg issue

🥚🐔 😆 
That's unfortunate! 

Thanks for your contribution, it looks good 👍🏻

**Pull request merged**
